#! /bin/sh

# Restore wallpaper
# bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

## Workspace 1 (Classes)
bspc rule -a zoom desktop='^1' follow=on focus=on
bspc rule -a Chat desktop='^1' state=floating
bspc rule -a FreeTube desktop='^1' follow=on focus=on

## Workspace 2 (Web Browser)
bspc rule -a LibreWolf desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on

## Workspace 3 (Terminal)
bspc rule -a Alacritty desktop='^3' follow=on focus=on

## Workspace 4 (Social)
bspc rule -a discord desktop='^4' follow=on focus=on

## Workspace 5 (Files)
bspc rule -a Thunar desktop='^5' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^5' follow=on focus=on state=floating

## Workspace 6 (Media)
# Email
bspc rule -a Geary desktop='^6' follow=on focus=on
bspc rule -a Zathura desktop='^6' follow=on focus=on
bspc rule -a vlc desktop='^6' follow=on focus=on
bspc rule -a obs desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Gimp desktop='^6' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^6' follow=on focus=on

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad Gpick)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey conky

# Launch Conky
# conky -c $HOME/.config/conky/axyl.conkyrc

# Launch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Source Code Pro Medium 10" \
-lb "#282a36FF" -lf "#f8f8f2FF" -lfr "#bd93f9FF" \
-nb "#282a36FF" -nf "#f8f8f2FF" -nfr "#bd93f9FF" \
-cb "#282a36FF" -cf "#BF616AFF" -cfr "#BF616AFF" &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start compositor
picom --config $HOME/.config/bspwm/picom.conf &

# Feh
feh --bg-fill ~/Pictures/tokyo-wallpaper.jpg &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"chadracula\",/g" $HOME/.config/nvim/lua/chadrc.lua

# Remap control key and caps lock
xmodmap ~/.config/bspwm/swapkeys -display :0 &
